### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.NSAudienceConfigParameter
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameter
  id: NSAudienceConfigParameter
  langs:
  - crmscript
  children:
  - CRMScript.NetServer.NSAudienceConfigParameter.#ctor
  - CRMScript.NetServer.NSAudienceConfigParameter.GetAudienceLayoutId()
  - CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedBy()
  - CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedDate()
  - CRMScript.NetServer.NSAudienceConfigParameter.GetName()
  - CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedBy()
  - CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedDate()
  - CRMScript.NetServer.NSAudienceConfigParameter.GetValue()
  - CRMScript.NetServer.NSAudienceConfigParameter.SetAudienceLayoutId(Integer)
  - CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedBy(String)
  - CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedDate(DateTime)
  - CRMScript.NetServer.NSAudienceConfigParameter.SetName(String)
  - CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedBy(String)
  - CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedDate(DateTime)
  - CRMScript.NetServer.NSAudienceConfigParameter.SetValue(String)
  name: NSAudienceConfigParameter
  nameWithType: NSAudienceConfigParameter
  fullName: CRMScript.NetServer.NSAudienceConfigParameter
  type: Class
  summary: 
  example: 
- uid: CRMScript.NetServer.NSAudienceConfigParameter.#ctor
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.#ctor
  id: '#ctor'
  so.intellisense: Void.NSAudienceConfigParameter
  langs:
  - crmscript
  name: '#ctor'
  nameWithType: NSAudienceConfigParameter.#ctor
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.#ctor
  type: Constructor
  summary: 
  remarks: 
  syntax: 
    content: NSAudienceConfigParameter
  example: 
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetAudienceLayoutId()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetAudienceLayoutId()
  id: 'GetAudienceLayoutId()'
  so.intellisense: NSAudienceConfigParameter.GetAudienceLayoutId
  langs:
  - crmscript
  name: 'GetAudienceLayoutId()'
  nameWithType: NSAudienceConfigParameter.GetAudienceLayoutId()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetAudienceLayoutId()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Integer GetAudienceLayoutId()
    parameters: []
    return:
      type: CRMScript.Global.Integer
      description: The ID of the Audience layout this configuration setting belongs to
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nInteger audienceLayoutId = thing.GetAudienceLayoutId();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedBy()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedBy()
  id: 'GetCreatedBy()'
  so.intellisense: NSAudienceConfigParameter.GetCreatedBy
  langs:
  - crmscript
  name: 'GetCreatedBy()'
  nameWithType: NSAudienceConfigParameter.GetCreatedBy()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedBy()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: String GetCreatedBy()
    parameters: []
    return:
      type: CRMScript.Global.String
      description: Name of the person that created the configuration parameter
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString createdBy = thing.GetCreatedBy();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedDate()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedDate()
  id: 'GetCreatedDate()'
  so.intellisense: NSAudienceConfigParameter.GetCreatedDate
  langs:
  - crmscript
  name: 'GetCreatedDate()'
  nameWithType: NSAudienceConfigParameter.GetCreatedDate()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetCreatedDate()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: DateTime GetCreatedDate()
    parameters: []
    return:
      type: CRMScript.Global.DateTime
      description: The date and time the configuration parameter was created
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nDateTime createdDate = thing.GetCreatedDate();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetName()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetName()
  id: 'GetName()'
  so.intellisense: NSAudienceConfigParameter.GetName
  langs:
  - crmscript
  name: 'GetName()'
  nameWithType: NSAudienceConfigParameter.GetName()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetName()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: String GetName()
    parameters: []
    return:
      type: CRMScript.Global.String
      description: The name of the configuration parameter
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString name = thing.GetName();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedBy()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedBy()
  id: 'GetUpdatedBy()'
  so.intellisense: NSAudienceConfigParameter.GetUpdatedBy
  langs:
  - crmscript
  name: 'GetUpdatedBy()'
  nameWithType: NSAudienceConfigParameter.GetUpdatedBy()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedBy()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: String GetUpdatedBy()
    parameters: []
    return:
      type: CRMScript.Global.String
      description: Name of the person that last updated the configuration parameter
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString updatedBy = thing.GetUpdatedBy();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedDate()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedDate()
  id: 'GetUpdatedDate()'
  so.intellisense: NSAudienceConfigParameter.GetUpdatedDate
  langs:
  - crmscript
  name: 'GetUpdatedDate()'
  nameWithType: NSAudienceConfigParameter.GetUpdatedDate()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetUpdatedDate()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: DateTime GetUpdatedDate()
    parameters: []
    return:
      type: CRMScript.Global.DateTime
      description: The date and time the configuration parameter was last updated
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nDateTime updatedDate = thing.GetUpdatedDate();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.GetValue()
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.GetValue()
  id: 'GetValue()'
  so.intellisense: NSAudienceConfigParameter.GetValue
  langs:
  - crmscript
  name: 'GetValue()'
  nameWithType: NSAudienceConfigParameter.GetValue()
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.GetValue()
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: String GetValue()
    parameters: []
    return:
      type: CRMScript.Global.String
      description: The value of the configuration parameter
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString value = thing.GetValue();</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetAudienceLayoutId(Integer)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetAudienceLayoutId(Integer)
  id: 'SetAudienceLayoutId(Integer)'
  so.intellisense: NSAudienceConfigParameter.SetAudienceLayoutId
  langs:
  - crmscript
  name: 'SetAudienceLayoutId(Integer)'
  nameWithType: NSAudienceConfigParameter.SetAudienceLayoutId(Integer)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetAudienceLayoutId(Integer)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetAudienceLayoutId(Integer audienceLayoutId)
    parameters:
    - id: audienceLayoutId
      type: CRMScript.Global.Integer
      description: The ID of the Audience layout this configuration setting belongs to
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nInteger audienceLayoutId;\nthing.SetAudienceLayoutId(audienceLayoutId);</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedBy(String)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedBy(String)
  id: 'SetCreatedBy(String)'
  so.intellisense: NSAudienceConfigParameter.SetCreatedBy
  langs:
  - crmscript
  name: 'SetCreatedBy(String)'
  nameWithType: NSAudienceConfigParameter.SetCreatedBy(String)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedBy(String)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetCreatedBy(String createdBy)
    parameters:
    - id: createdBy
      type: CRMScript.Global.String
      description: Name of the person that created the configuration parameter
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString createdBy;\nthing.SetCreatedBy(createdBy);</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedDate(DateTime)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedDate(DateTime)
  id: 'SetCreatedDate(DateTime)'
  so.intellisense: NSAudienceConfigParameter.SetCreatedDate
  langs:
  - crmscript
  name: 'SetCreatedDate(DateTime)'
  nameWithType: NSAudienceConfigParameter.SetCreatedDate(DateTime)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetCreatedDate(DateTime)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetCreatedDate(DateTime createdDate)
    parameters:
    - id: createdDate
      type: CRMScript.Global.DateTime
      description: The date and time the configuration parameter was created
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nDateTime createdDate;\nthing.SetCreatedDate(createdDate);</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetName(String)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetName(String)
  id: 'SetName(String)'
  so.intellisense: NSAudienceConfigParameter.SetName
  langs:
  - crmscript
  name: 'SetName(String)'
  nameWithType: NSAudienceConfigParameter.SetName(String)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetName(String)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetName(String name)
    parameters:
    - id: name
      type: CRMScript.Global.String
      description: The name of the configuration parameter
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString name;\nthing.SetName(name);</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedBy(String)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedBy(String)
  id: 'SetUpdatedBy(String)'
  so.intellisense: NSAudienceConfigParameter.SetUpdatedBy
  langs:
  - crmscript
  name: 'SetUpdatedBy(String)'
  nameWithType: NSAudienceConfigParameter.SetUpdatedBy(String)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedBy(String)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetUpdatedBy(String updatedBy)
    parameters:
    - id: updatedBy
      type: CRMScript.Global.String
      description: Name of the person that last updated the configuration parameter
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString updatedBy;\nthing.SetUpdatedBy(updatedBy);</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedDate(DateTime)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedDate(DateTime)
  id: 'SetUpdatedDate(DateTime)'
  so.intellisense: NSAudienceConfigParameter.SetUpdatedDate
  langs:
  - crmscript
  name: 'SetUpdatedDate(DateTime)'
  nameWithType: NSAudienceConfigParameter.SetUpdatedDate(DateTime)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetUpdatedDate(DateTime)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetUpdatedDate(DateTime updatedDate)
    parameters:
    - id: updatedDate
      type: CRMScript.Global.DateTime
      description: The date and time the configuration parameter was last updated
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nDateTime updatedDate;\nthing.SetUpdatedDate(updatedDate);</code></pre>\n"
- uid: CRMScript.NetServer.NSAudienceConfigParameter.SetValue(String)
  commentId: M:CRMScript.NetServer.NSAudienceConfigParameter.SetValue(String)
  id: 'SetValue(String)'
  so.intellisense: NSAudienceConfigParameter.SetValue
  langs:
  - crmscript
  name: 'SetValue(String)'
  nameWithType: NSAudienceConfigParameter.SetValue(String)
  fullName: CRMScript.NetServer.NSAudienceConfigParameter.SetValue(String)
  type: Method
  summary: ""
  remarks: 
  syntax: 
    content: Void SetValue(String value)
    parameters:
    - id: value
      type: CRMScript.Global.String
      description: The value of the configuration parameter
    return:
      type: CRMScript.Global.Void
  example: 
  - "\n<pre><code>NSAudienceConfigParameter thing;\nString value;\nthing.SetValue(value);</code></pre>\n"
references:
- uid: CRMScript.NetServer.NSAudienceConfigParameter
  commentId: T:CRMScript.NetServer.NSAudienceConfigParameter
  isExternal: true
  name: NSAudienceConfigParameter
  nameWithType: NSAudienceConfigParameter
  fullName: CRMScript.NetServer.NSAudienceConfigParameter
- uid: CRMScript.Global.Integer
  commentId: T:CRMScript.Global.Integer
  isExternal: true
  name: Integer
  nameWithType: Integer
  fullName: CRMScript.Global.Integer
- uid: CRMScript.Global.String
  commentId: T:CRMScript.Global.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: CRMScript.Global.String
- uid: CRMScript.Global.DateTime
  commentId: T:CRMScript.Global.DateTime
  isExternal: true
  name: DateTime
  nameWithType: DateTime
  fullName: CRMScript.Global.DateTime
- uid: CRMScript.Global.Void
  commentId: T:CRMScript.Global.Void
  isExternal: true
  name: Void
  nameWithType: Void
  fullName: CRMScript.Global.Void